import Foundation
import Security
protocol AIKeychainStoring:Sendable{func read(service:String,account:String)throws->String?;func save(_ value:String,service:String,account:String)throws;func delete(service:String,account:String)throws}
enum AIKeychainError:Error,Equatable,Sendable{case status(OSStatus)}
struct KeychainAIKeyStore:AIKeychainStoring,Sendable{static let service="com.romeoke.RomeoDailyLedger.ai";let accessGroup:String?;init(accessGroup:String?=nil){self.accessGroup=accessGroup};func read(service:String=KeychainAIKeyStore.service,account:String="apiKey")throws->String?{var q:[CFString:Any]=[kSecClass:kSecClassGenericPassword,kSecAttrService:service,kSecAttrAccount:account,kSecReturnData:true,kSecMatchLimit:kSecMatchLimitOne];if let accessGroup{q[kSecAttrAccessGroup]=accessGroup};var r:CFTypeRef?;let s=SecItemCopyMatching(q as CFDictionary,&r);if s==errSecItemNotFound{return nil};guard s==errSecSuccess else{throw AIKeychainError.status(s)};return (r as? Data).flatMap{String(data:$0,encoding:.utf8)}};func save(_ value:String,service:String=KeychainAIKeyStore.service,account:String="apiKey")throws{var q:[CFString:Any]=[kSecClass:kSecClassGenericPassword,kSecAttrService:service,kSecAttrAccount:account];if let accessGroup{q[kSecAttrAccessGroup]=accessGroup};let a:[CFString:Any]=[kSecValueData:Data(value.utf8),kSecAttrAccessible:kSecAttrAccessibleAfterFirstUnlock];let u=SecItemUpdate(q as CFDictionary,a as CFDictionary);if u==errSecItemNotFound{var add=q;a.forEach{add[$0.key]=$0.value};let s=SecItemAdd(add as CFDictionary,nil);guard s==errSecSuccess else{throw AIKeychainError.status(s)}}else if u != errSecSuccess{throw AIKeychainError.status(u)}};func delete(service:String=KeychainAIKeyStore.service,account:String="apiKey")throws{var q:[CFString:Any]=[kSecClass:kSecClassGenericPassword,kSecAttrService:service,kSecAttrAccount:account];if let accessGroup{q[kSecAttrAccessGroup]=accessGroup};let s=SecItemDelete(q as CFDictionary);guard s==errSecSuccess || s==errSecItemNotFound else{throw AIKeychainError.status(s)}}}

struct DisabledAIKeyStore: AIKeychainStoring, Sendable {
    func read(service: String, account: String) throws -> String? { nil }
    func save(_ value: String, service: String, account: String) throws {}
    func delete(service: String, account: String) throws {}
}
