import Foundation
enum AIProtocol:String,Codable,CaseIterable,Identifiable,Sendable{case chatCompletions,responses;var id:String{rawValue};var displayName:String{self == .chatCompletions ? "Chat Completions":"Responses"}}
struct AIConfiguration:Codable,Equatable,Sendable{var protocolType:AIProtocol;var baseURL:URL;var model:String;var allowsLedgerData:Bool;init(protocolType:AIProtocol = .chatCompletions,baseURL:URL = URL(string:"https://api.openai.com/v1")!,model:String = "",allowsLedgerData:Bool = false){self.protocolType=protocolType;self.baseURL=baseURL;self.model=model;self.allowsLedgerData=allowsLedgerData}}
struct AILedgerDraft:Codable,Equatable,Sendable{var kind:EntryKind;var amount:Decimal;var currency:String;var date:Date;var note:String;var category:String
 init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); kind = try c.decode(EntryKind.self, forKey: .kind); amount = try c.decode(Decimal.self, forKey: .amount); currency = try c.decode(String.self, forKey: .currency); note = try c.decode(String.self, forKey: .note); category = try c.decode(String.self, forKey: .category); let value = try c.decode(String.self, forKey: .date); let f = ISO8601DateFormatter(); f.formatOptions = [.withFullDate]; guard let parsed = f.date(from: value) else { throw AIClientError.invalidStructuredResult("Invalid date") }; date = parsed }
 private enum CodingKeys: String, CodingKey { case kind, amount, currency, date, note, category }
}
struct AILedgerDraftEnvelope:Codable,Equatable,Sendable{var entries:[AILedgerDraft]}
enum AIClientError:LocalizedError,Equatable,Sendable{case apiKeyMissing,invalidBaseURL,invalidModel,network(String),httpStatus(Int,String?),responseDecoding(String),invalidStructuredResult(String);var errorDescription:String?{switch self{case .apiKeyMissing:return "API key is missing.";case .invalidBaseURL:return "The API base URL is invalid.";case .invalidModel:return "The model name is missing.";case let .network(m):return "Network request failed: \(m)";case let .httpStatus(c,m):return "The AI service returned HTTP \(c).\(m.map{" \($0)"} ?? "")";case let .responseDecoding(m):return "Unable to decode the AI response: \(m)";case let .invalidStructuredResult(m):return "The AI returned an invalid ledger result: \(m)"}}}
